language: python

python:
 - "2.7"

env:
 - DJANGO=1.5

install:
 - pip install -q Django==$DJANGO --use-mirrors
 - pip install python-swiftclient
 - pip install git+git://github.com/bors-ltd/django-icons-mimetypes.git#egg=django-icons-mimetypes
 - pip install Pillow

script: python runtests.py

notifications:
 email:
  recipients:
   - github@cschwede.de
